spring:
  application:
    name: nexuspay
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  logging:
    level:
      org:
        springframework.security: DEBUG
        springframework.web.access: DEBUG
        hibernate:
          type: trace
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    aws:
      region:
        static: sa-east-1
      credentials:
        access-key: test
        secret-key: test
      endpoint: http://localstack:4566
      sqs:
        endpoint: http://localstack:4566
        listener:
          acknowledgement-mode: ON_SUCCESS
events:
  queues:
    user-registration: nexuspay-user-registered-queue

api:
  security:
    token: ${JWT_SECRET:my-secret}
